In [1]:
print(10&4+3)

2


In [2]:
print(10&7)

2


In [3]:
print(10&4)

0


In [4]:
print(7+2&4+3&9)

1


In [5]:
print(10|3&4)

10


In [6]:
print(3&4)

0


In [7]:
print(10|0)

10


In [8]:
print(10|3)

11


In [9]:
print(11&4)

0


In [10]:
print(3&6^7)

5


In [11]:
print(3&6)

2


In [12]:
print(2^7)

5


In [13]:
print(2|3^5)

6


In [14]:
print(2|3)

3


In [15]:
print(3^5)

6


<h1>order of bitwise</h1>
<h2><b>~ (>) & (>) ^ (>) |</b></h2>

In [16]:
bin(14)

'0b1110'

In [19]:
10 & 4 ~ 2

SyntaxError: invalid syntax (2482061267.py, line 1)

In [20]:
6|3&9+6

7

In [21]:
2~4^3*2  #invalid

SyntaxError: invalid syntax (3991895762.py, line 1)

In [22]:
~2

-3

In [23]:
~9+4&6

2

In [24]:
~(4^3)+3

-5

In [25]:
14>>1

7

In [26]:
14>>2

3

In [27]:
14>>3

1

In [28]:
14<<1

28

In [29]:
14<<2

56

In [30]:
14<<3

112

In [31]:
-10+4&6

2

In [33]:
~6&6

0

In [34]:
-10+4

-6

In [35]:
-6&6

2

In [36]:
6&6

6

In [37]:
bin(-6)

'-0b110'

<h2><b>~n=-(n+1)<br>
-n=~n+1
</b></h2>

In [40]:
7<<1


14

 <h1> even 1's : 0<br>
    odd 1's : 1<br>
    
xor of number itself is 0<br>
xor of number with 0 is number itself<br> 
   5>>1:=>>2<br>
    5/2==2
    
    <br>
    5<<1==10
    5*2==10
</h1>

In [42]:
1^2^3

0

<table>
    <tr>
        <td>
            A 
        </td>
        <td>
             B 
        </td>
        <td>
            A^B
        </td>
    </tr>
    <tr>
        <td>
          0 
        </td>
        <td>
          0 
        </td>
        <td>
          0 
        </td>
    </tr>
    <tr>
        <td>
          1
        </td>
        <td>
          1 
        </td>
        <td>
          0
        </td>
    </tr>
    <tr>
        <td>
          1 
        </td>
        <td>
          0 
        </td>
        <td>
          1 
        </td>
    </tr>
    <tr>
        <td>
          0 
        </td>
        <td>
          1 
        </td>
        <td>
          1 
        </td>
    </tr>
    
   </table>

In [44]:
2**31

2147483648

In [4]:
def missing_no(n,arr):
    chk=0
    for i in range(len(arr)):
        if arr[i]==1:
            chk+=1
        if arr[i]<0:
            arr[i]=1
        
    if chk==0:
        return 1
    for i in range(len(arr)):
        val=abs(arr[i])-1
        if val>=0 and val<len(arr):
            arr[val]=-1*abs(arr[val])
    for i in range(len(arr)):
        if arr[i]>0:
            return i+1
    return len(arr)+1
n=int(input())
arr=list(map(int,input().split()))
print(missing_no(n,arr))

5
1 2 3 5
4


In [15]:
def miss(arr):
    nums=set(arr)
    l=0
    while l in nums:
        l+=1
    return l
arr=list(map(int,input().split()))
res=miss(arr)
print(res)


1 2 3 5
0


In [14]:
b=input()
a=[int(x) for x in b.split()]
print(a)
for i in range(len(a)):
    if i not in a:
        print(i)
        break
        

0 1 2 3 4
[0, 1, 2, 3, 4]


In [16]:
#in the given an array every numbeer occur twice only one nmber occurs one time 
def sno(n):
    c=0
    for i in n:
        c^=i
    return c
n=list(map(int,input().split()))
x=sno(n)
print(x)


1 5 1 2 3 2 3
5


In [ ]:
#in triples
def sno(n):
    ones=0
    twos=0
    for i in range(len(n)):
        twos=twos^(ones&n[i])
        ones=ones^n[i]
        cmbits=~(ones&twos)
        ones=ones&cmbits
        twos=twos&cmbits
    return ones
n=list(map(int,input().split()))
x=sno(n)
print(x)

In [20]:
#swapping two numbers using xor
a=10
b=20
print(a,b)
a=a^b
b=a^b
a=a^b
print(a,b)

10 20
20 10


In [22]:
#give a number n abnnd integer i find out if ith bit is set or not?
n=int(input())
i=2
if 1&(n>>i)==1:
    print("set bit")
else:
    print("not set")
print()



5
set bit



In [31]:
n=int(input())
i=4
if n&(1<<i)==0:
    print("not set bit")
else:
    print("set bit")


10
not set bit


In [40]:
#for given number n find out xor of all numbers
n=int(input())
c=0
for i in range(1,n+1):
    c=c^i
print(c)

5
1


In [83]:
#O(1)
#xor of all numbers
n=int(input())
xor=0
if n%4==0:
    print(n)
elif n%4==1:
    print(1)
elif n%4==2:
    print(n+1)
elif n%4==3:
    print(0)


3
0


In [51]:
n=int(input())
if n&(n-1)==0:
    print("yes")
else:
    print("no")

5
no


In [57]:
#xor for range numbers
l=int(input())
r=int(input())
for i in range(l,r+1):
    c=c^i
print(c)

2
4
5


In [88]:
import numpy as np
l=int(input())
r=int(input())
x=np.arange(1,r+1)
y=np.arange(1,l)
print(x,y)
def xor(n):
    xor=0
    if n%4==0:
        print(n)
    elif n%4==1:
        print(1)
    elif n%4==2:
        print(n+1)
    elif n%4==3:
        print(0)
xor(len(x))
xor(len(y))

4
9
[1 2 3 4 5 6 7 8 9] [1 2 3]
1
0


In [61]:
import numpy as np
np.arange(4)

array([0, 1, 2, 3])

In [67]:
np.arange(1,4)

array([1, 2, 3])

In [72]:
#even number or not usign xor
n=int(input())
if n&1==0:
    print("even")
else:
    print("odd")

4
even


In [91]:
def fibonacci(n):
    if n<=0:
        return 0
    elif n==1:
        return 1
    else:
        a,b=0,1
        for j in range(2,n+1):
            a,b=b,a+b
        return b
n=int(input())
x=fibonacci(n)
print(x)



7
13


In [93]:
def tower_of_hanoi(disks,source,auxiliary,target):  
    if(disks==1):  
        print(source,target)  
        return  
    tower_of_hanoi(disks-1,source,target,auxiliary)  
    print(disks,source,target)
    tower_of_hanoi(disks-1,auxiliary,source,target)  
disks=int(input())  
tower_of_hanoi(disks, 'A', 'B', 'C') 

3
A C
2 A B
C B
3 A C
B A
2 B C
A C
